- cmon/api/backup.go
- cmon/backup.go
- multi/api/backups.go
- multi/backups.go
I just hardcoded the value in the request.
This will be a breaking change for Hydra frontend, but well we can fix it too. I think is too much to have backwards compatibility.
Btw, backups/lists does not return full backups right? only 7 days back? just trying to confirm.
> Using backup records version 2

- cmon/api/cluster.go
- cmon/api/cmon_int.go
- cmon/api/host.go
https://severalnines.atlassian.net/browse/CCHYDRA-13 
Added some field sin cluster, and hosts
Also sorted fields alphabetically in hosts
> CCHYDRA-13 added missing fields in cluster and hosts

- multi/api/clusterlist.go
- multi/api/controllerstatus.go
- multi/clusters.go
- multi/controllers.go
> Force update of cluster list

- cmon/client.go
jira: https://severalnines.atlassian.net/browse/CLUS-4012
> CLUS-4012 add Expect: 100-continue

- Makefile
- README.md
jira: https://severalnines.atlassian.net/browse/CLUS-3773
> CLUS-3773 ccmgr.yaml config docs & make commade to debug builder

- config/config.go
- multi/authentication.go
- rpcserver/server.go
- rpcserver/session/session.go
Jira: https://severalnines.atlassian.net/browse/CLUS-3986
- Added LastActive prop to session
- Created schedule to execute old sessions cleanup
- Default session time minimum to 30 min
- Set maxage = 0 to cookie so it will expire with browser tab session
- refreshing session on /check request
fe pr https://github.com/severalnines/frontend-hub/pull/19
> Keep browser session alive

- cmon/client.go
- multi/controllers.go
- multi/router/router.go
jira: https://severalnines.atlassian.net/browse/CLUS-4003
> CLUS-4003 reset session and invalidate cache on controller update

- multi/backups.go
- multi/controllers.go
jiras:
- https://severalnines.atlassian.net/browse/CLUS-4184
- https://severalnines.atlassian.net/browse/CLUS-4185
> CLUS-4184, CLUS-4185 bugfix

- Makefile
- cmon/client.go
- multi/controllers.go
jira: https://severalnines.atlassian.net/browse/CLUS-3774
controller cookie was missing in reverse proxy handler
> CLUS-3774 add controller cookie to request in reverse proxy

- rpcserver/server.go
jira: https://severalnines.atlassian.net/browse/CLUS-4437
> CLUS-4437 add security headers & adjust Cache-Control

- ccmgradm/main.go
jira: https://severalnines.atlassian.net/browse/CLUS-4384
cmon_ssh_host parameter was missing after init
> CLUS-4384 add cmon ssh host on init

- rpcserver/server.go
https://severalnines.atlassian.net/browse/CLUS-4437
had alert from scanner about /assets/ directory
> CLUS-4437 show index.html if directory is request

- config/config.go
- env/env_dev.go
- env/env_prod.go
- main.go
- rpcserver/server.go
jira: https://severalnines.atlassian.net/browse/CLUS-4457
- in production builds files not allowed to be served outside of /var/www
- resolving and validating symlink path
> CLUS-4457 validate frontend_path & request path

- rpcserver/server.go
jira: https://severalnines.atlassian.net/browse/CLUS-4563
> CLUS-4563 do not fail cmon-proxy to start if frontend_path is invalid

- cmon/client.go
- config/config.go
- multi/api/controllerstatus.go
- multi/authentication.go
- multi/controllers.go
- multi/router/router.go
jira: https://severalnines.atlassian.net/browse/CLUS-4726
goes with: https://github.com/severalnines/frontend-hub/pull/203
> CLUS-4726 merge ldap and cmon authentication

- .github/workflows/ccmgr-build-push.yaml
jira: https://severalnines.atlassian.net/browse/CLUS-5298
> CLUS-5298 build ccmgr image workflow

- config/config.go
- multi/api/k8s.go
- multi/k8s.go
- rpcserver/server.go
Jira: https://severalnines.atlassian.net/browse/CLUS-5555
Added endpoint for enable/disable k8s in config
>  CLUS-5555 enable disable k8s in UI

- multi/api/controlleraddremove.go
- multi/api/mcc.go
- multi/api/user.go
- multi/authentication.go
- multi/controllers.go
- multi/mcc.go
- rpcserver/server.go
Jira: https://severalnines.atlassian.net/browse/CLUS-5839
Added new endpoints to check elevated session, elevate session, and exit elevated session.
A flag named "elevated" will define if use has rights to do CRUD ops to controllers
> Clus 5839 mcc enable flow

- multi/controllers.go
Jira: https://severalnines.atlassian.net/browse/CLUS-5839
> CLUS-5839 fix controller test connection

- config/config.go
- rpcserver/server.go
Jira: https://severalnines.atlassian.net/browse/CLUS-5903
- ioutil deprecated
- added handler for `/cc-license`
> CLUS-5903 license request

- multi/controllers.go
jira: https://severalnines.atlassian.net/browse/CLUS-5954
Truncate controller name to 60 chars
> CLUS-5954 truncate controller name

- config/config.go
- multi/api/mcc.go
- multi/mcc.go
Jira https://severalnines.atlassian.net/browse/CLUS-5931
Only hotfix for patch
> CLUS-5931 fix ldap connection when enabling mcc

- README.md
- multi/controllers.go
- rpcserver/server.go
original: https://github.com/severalnines/cmon-proxy/pull/50
> CLUS-5978 proxying requests to cmon-ssh when for single controller mode

- .github/workflows/docker-image-build-push.yaml
- ccmgradm/main.go
- docker/Dockerfile
jira: https://severalnines.atlassian.net/browse/CLUS-5945
> CLUS-5945 docker image build workflow

- .github/workflows/docker-image-build-push.yaml
jira: https://severalnines.atlassian.net/browse/CLUS-6060
> CLUS-6060 add build number to image tag and validate release branch name

- .github/workflows/patch-to-release.yaml
- rpcserver/server.go
Jira: https://severalnines.atlassian.net/browse/CLUS-6054
Forwarding ip from client and some other headers
> CLUS-6054 added new headers to send origin IP

- rpcserver/server.go
jiras:
https://severalnines.atlassian.net/browse/CLUS-5665
https://severalnines.atlassian.net/browse/CLUS-5666
> CLUS-5665 CLUS-5666 proxy PUT and DELETE to kuber-proxy

- README.md
- config/config.go
- rpcserver/server.go
jira: https://severalnines.atlassian.net/browse/CLUS-6083
> CLUS-6083 support letsencrypt

- config/config.go
- multi/controllers.go
- multi/controllers_test.go
- rpcserver/server.go
Jira: https://severalnines.atlassian.net/browse/CLUS-6107
Added controller_id to instances
> CLUS-6107 controller_id in instances
